### ISSUE TITLE
Home Page Development

### ISSUE THREAD

**Issue by MAYALURI-ANUSHA** [LanguageTranslationOrg/LanguageTranslationSystem#24]
@Srivarsan09 
@harshakun 

Prepare content for the home page in all 10 languages and also suggest any ideas for the development of home page

**Comment by harshakun** [comment]
Here is the JSON file that consists of content for all languages. This file will be used in addition feature- Translating entire page into the desired language 

[languages.json](https://github.com/user-attachments/files/16017948/languages.json)

this issue can be closed as all the work related to this issue is done
